### PR TITLE
assorted-biscuits-setdecorations: fix setDecorations not invoked if d…

### LINKED ISSUE #5: Assorted Biscuits - setDecorations issue on Theia IDE
Referencing bug opened on Theia: https://github.com/eclipse-theia/theia/issues/8902

**Bug Description:**
Appears only after modifying the file, disappears when switching to another file.
Works in vscode.

**Steps to Reproduce:**
Install Assorted Biscuits extensions (codebiscuits.assorted-biscuits) from Open VSX Registry.
Open a *.json file with data
Modify the file to see text by the end brackets
Switch to another file
Go back to the .json file and see text disappeared

https://user-images.githubusercontent.com/71069170/104839321-e2667100-58c8-11eb-846d-64bf2eaeb7c3.mp4

After investigating 8902, IMO, a small code improvement should be added to prevent invoking setDecorations with empty decorations array:
image

Opening a PR for that.

### PR DESCRIPTION
**Pull request by danarad05**
…ecorations array is empty

Signed-off-by: Dan Arad <dan.arad@sap.com>

**What it does**
Fixes #5 

**How to test**
1. Compile and package extension
2. Add to Theia plugins
3. Open json file to test

### CODE REVIEW

**Comment by danarad05** [comment]
@cmgriffing 
Hi, hope you can review PR. If you have any questions please let me know
Thanks
Dan

**Comment by cmgriffing** [comment]
Yes, sorry for the delay. I have been a bit busy with work and streaming.

Thanks for looking into this. This looks great. I wanted to pull it down and test it just to be sure.

The reasoning is that we want to make sure we clear biscuits from a file that might not have any after some changes.

eg:
Assuming a min line distance of 4:

```javascript
function foo() {
///
///
///
///
///
} <- foo

// then we change it to
function foo() {
///
}

```

If we don't set empty decorations, does it still show up when it shouldn't?
I'm not certain and that's what I wanted to verify.

**Comment by cmgriffing** [comment]
Ok sorry for the delay. Thanks for the PR.

**Comment by amiramw** [comment]
@cmgriffing do you plan to publish a new version with the fix to https://open-vsx.org/extension/CodeBiscuits/assorted-biscuits ?

**Comment by cmgriffing** [comment]
It has been published in version 0.0.21. Thanks again.

**Pull request merged**
